### ISSUE TITLE
请修改配置文件中的 google_analytics tracking code

### ISSUE THREAD

**Issue by ArthurChiao** [defineYIDA/defineYIDA.github.io#4]
hello，配置文件中的这个 code 是个人申请的，

https://github.com/defineYIDA/defineYIDA.github.io/blob/master/_config.yml#L38

用于跟踪自己 site 的访问信息。

还请你将这个 code 置空，或者自己申请一个，否则会影响我这边的统计，谢谢。

**Comment by defineYIDA** [comment]
> hello，配置文件中的这个 code 是个人申请的，
> 
> https://github.com/defineYIDA/defineYIDA.github.io/blob/master/_config.yml#L38
> 
> 用于跟踪自己 site 的访问信息。
> 
> 还请你将这个 code 置空，或者自己申请一个，否则会影响我这边的统计，谢谢。

抱歉影响到你了，已删除。

**Comment by ArthurChiao** [comment]
没关系，多谢！
